# MongoDB, Postgres, Redis, Elasticsearch, Kibana, Mysql, Postgres
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - 27018:27017
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: riders_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-auth:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authDb
    ports:
      - 5133:5432
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data:
  postgres_auth_data:
  mongo_data:
